/**
 * SADCAS-aligned transfusion incident report builder.
 *
 * Produces a self-contained, printable HTML incident report from a haemovigilance
 * adverse-event record — the audit-ready artefact a Hospital Transfusion Committee
 * presents at accreditation review (SADCAS / ISO 15189 transfusion safety).
 *
 * This is demonstration formatting, not a certified regulatory submission.
 */

export const FACILITY_DEFAULT = {
  name: 'Gaborone Private Hospital',
  group: 'Life Healthcare Group',
  bloodBank: 'Hospital Blood Bank',
  accreditation: 'SADCAS / ISO 15189 transfusion safety',
}

// WHO/ISBT imputability scale used in haemovigilance classification.
const IMPUTABILITY = {
  SEVERE: 'Probable',
  FATAL: 'Definite',
  MODERATE: 'Possible',
  MILD: 'Possible',
}

function fmt(dt) {
  if (!dt) return '—'
  return new Date(dt).toLocaleString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
}

/** Build a structured SADCAS incident report object + printable HTML. */
export function buildSadcasIncidentReport(event, facility = FACILITY_DEFAULT) {
  const incidentId = `SADCAS-INC-${(event.id || 'AE').replace(/[^A-Za-z0-9-]/g, '')}`
  const imputability = IMPUTABILITY[event.severity] || 'Possible'
  const generatedAt = new Date().toISOString()

  const sections = [
    ['Incident reference', incidentId],
    ['Source event ID', event.id || '—'],
    ['Facility', `${facility.name} — ${facility.bloodBank}`],
    ['Accreditation framework', facility.accreditation],
    ['Patient reference', event.patientRef || '—'],
    ['Implicated unit', event.unitId || 'Not identified'],
    ['Reaction type', event.eventType || '—'],
    ['Severity grade', event.severity || '—'],
    ['WHO/ISBT imputability', imputability],
    ['Reported at', fmt(event.reportedAt)],
    ['Current status', event.status || '—'],
    ['Report generated', fmt(generatedAt)],
  ]

  const rows = sections.map(
    ([k, v]) => `<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`,
  ).join('')

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>${esc(incidentId)} — Transfusion Incident Report</title>
<style>
  body { font-family: Arial, Helvetica, sans-serif; color: #111; margin: 40px; line-height: 1.5; }
  header { border-bottom: 3px solid #A81F38; padding-bottom: 12px; margin-bottom: 24px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  .sub { color: #555; font-size: 12px; }
  .tag { display:inline-block; background:#A81F38; color:#fff; font-size:11px; padding:2px 8px; border-radius:4px; letter-spacing:.08em; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { border: 1px solid #ccc; padding: 8px 10px; text-align: left; font-size: 13px; vertical-align: top; }
  th { background: #f4f4f6; width: 230px; }
  h2 { font-size: 14px; margin: 24px 0 6px; border-left: 4px solid #A81F38; padding-left: 8px; }
  .narrative { border:1px solid #ccc; padding:12px; font-size:13px; min-height:60px; white-space:pre-wrap; }
  .sign { display:flex; gap:40px; margin-top:40px; }
  .sign div { flex:1; border-top:1px solid #333; padding-top:6px; font-size:12px; color:#333; }
  footer { margin-top:32px; font-size:11px; color:#777; border-top:1px solid #eee; padding-top:10px; }
</style></head>
<body>
  <header>
    <span class="tag">SADCAS — CONFIDENTIAL</span>
    <h1>Transfusion Reaction Incident Report</h1>
    <p class="sub">${esc(facility.name)} · ${esc(facility.group)} · Hospital Transfusion Committee</p>
  </header>

  <h2>Incident summary</h2>
  <table><tbody>${rows}</tbody></table>

  <h2>Clinical narrative</h2>
  <div class="narrative">${esc(event.narrative || 'No narrative recorded.')}</div>

  <h2>Immediate actions taken</h2>
  <div class="narrative">Transfusion stopped; line maintained with saline; vitals monitored; unit and giving set returned to blood bank with post-reaction samples; clinical team and blood bank notified.</div>

  <h2>Committee investigation &amp; corrective action</h2>
  <div class="narrative">Root-cause analysis pending Hospital Transfusion Committee review. Classification, preventability and corrective/preventive actions (CAPA) to be recorded at the next committee sitting.</div>

  <div class="sign">
    <div>Reporting clinician — name / signature / date</div>
    <div>HTC chairperson — name / signature / date</div>
  </div>

  <footer>
    Generated by Bloodchain Transfuse — demonstration software. Not a certified regulatory submission.
    Incident ${esc(incidentId)} · generated ${esc(fmt(generatedAt))}.
  </footer>
</body></html>`

  return {
    incidentId,
    imputability,
    filename: `${incidentId}.html`,
    html,
  }
}
